### ISSUE TITLE
Features for v0.7.1 Release

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php#110]
For tracking progress on v0.7.1. Technically v0.7.1 is already out. I just mean to find a way to fit in a minor release. Should be released mid-February. The issues I'd like to cover:
- [ ] ~~add support for bower~~ (#108)
- [x] add boolean attribute support to pattern parameters (#109) ~~(add docs)~~
- [x] add the mustache code to "code view" (#97)
- [x] add ability to customize nav headings (#96) (add docs)
- [x] add `cmd+a` support in code view (#95)
- [x] add label support for nav items (#94) (add docs)
- [x] make sure PL specific code only loads when in the iframe (#67)
- [x] additional keyboard shortcuts (#114) ~~(add docs)~~
- [x] pattern search (#115)
- [x] make sure the config is written only after the migrations run
- [x] make sure order of patterns for `gatherPatternInfo()` is enforced (#113)
- [x] add query string support for opening annotation and code view by default (#38) ~~(add docs)~~
- [x] better (not great) support for IE9 (#125)

For launch:
- [x] update PL documentation
- [x] update README
- [x] update CHANGELOG
- [x] cut a v0.7.1 branch
- [x] merge with `master`
- [x] tag `master` with v0.7.1
- [x] update Releases
