### ISSUE TITLE
Features for v0.7.9 Release

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php#147]
For tracking progress on our next small release, v0.7.9. I just want to make sure we're on the same page in what we want to get done. Should be released end of March. The issues that the release should cover:
- [x] remove most everything in `public/` (#140)
- [x] add flag to "turn off" cacheBuster (#136) _done, needs approval_
- [x] add flag to generate _only_ patterns (#135) _done, needs approval_
- [x] add more config options with smarter defaults (#143)
- [x] document the config options on one page in the docs
- [x] fix icon font issues (#144)
- [x] fix dynamic height for menus (#145)
- [x] right align the sg-controls (#142)
- [x] remove CDN jquery (#138)

For launch:
- [x] update PL documentation
- [x] update README
- [x] update CHANGELOG
- [x] cut a v0.7.9 branch
- [x] merge with `master`
- [x] tag `master` with v0.7.9
- [x] update Releases
