### ISSUE TITLE
Features for v0.8.0 Release

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php#51]
For tracking progress on v0.8.0. Should be released at some point >.< The issues I'd like to cover:

 - [ ] add support for KSS as a plugin. include breakpoint & pattern reference support. (#34)
 - [ ] add support for Faker as a plugin. (#174)
 - [ ] ~~custom header and footers for top-level patterns~~ (#30)
 - [x] add multi-site support (#55)
 - [ ] ~~leave comments on annotations~~ (#91)
 - [ ] refactor styleguide.js (#92)
 - [ ] ~~browserstack integration~~ (#90)
 - [x] listItem customization (#167)
 - [ ] add lineages to "list view" (#160)
 - [x] make sure cmd+a for selecting text only fires when code view is up (#162)
 - [ ] ~~add keyboard shortcuts for nav~~ (#150)
 - [x] allow for chunking of _data.json (#141)
 - [ ] add support for _docs (#130)
 - [x] multiple classes for style modifier (#172)
 - [ ] annotation/code buttons on style guide view (#173)
 - [x] support the ability to extend to other pattern engines other than Mustache
 - [x] support data being defined in YAML in addition to JSON
 - [x] can use `link.[pattern-name]` within data to link to other patterns
 - [x] pattern parameters can support simple lists (#179)
 - [x] pattern parameters run a find & replace more like mustache (#178)
 - [x] only override `cmd+a` when code view is up (#162)
 - [x] json linter to provide better error messaging when there's a data load problem (#175)
 - [x] yaml linting for better error handling (catch symfony error)
 - [x] listItem loop number can be overridden via pattern parameters (#167)
 - [x] smarter sorting of MQs (#182)
 - [x] smarter selection of MQs (#253)
 - [x] search all of the project for MQs (#197)
 - [x] move shared header/footer out of `_patterns/atoms` and into `
 - [x] expand console options
 - [x] deprecate `core/builder.php` in favor of `core/console`
 - [x] add support for "snapshots"
 - [x] smarter lineage support (#191)
 - [x] view all pages for sections with pattern sub-types (e.g. atoms) (#203)
 - [x] ability to define custom mustache helpers (#209)
 - [x] event notification support for PLs back-end
 - [x] plugin system that attaches to various events in PL (#93)
 - [x] push plugin mark-up to the front-end viewer (code panel and nav bar)
 - [x] break out the "viewer" from PL proper. load nav via a JSON file. 
 - [x] break out the "demo" mustache files from PL proper into a separate "starter kit"
 - [ ] ability to organize patterns in nav via JSON in addition to file system
 - [x] annotations can be defined using Markdown
 - [x] multiple annotations can be defined in one Markdown file
 - [ ] ~~annotations can be defined along-side patterns~~
 - [x] pattern documentation via Markdown and YAML front-matter
 - [x] properly vendor pattern lab external libs using composer
 - [ ] ~~add composer to the distribution directly to limit a dependency but allow plug-ins to easily include dependencies~~ add an install/update method for composer
 - [x] fetch util to grab starter kits, plug-ins, and mustache helpers
 - [x] switch to defining pattern attributes as JSON instead of explicit javascript vars
 - [x] global pattern data class to better handle import and sharing data
 - [x] colorful console
 - [x] switch the console to use long commands as keys to make it easy to modify that for plug-ins
 - [x] allow for patterns and static assets to be exported minus any PL cruft (#40, #67, #141)
 - [x] allow the font size used for displaying the ems to be overridden via the config
 - [x] can hide individual patterns from "view all" view but make them available via the nav (#257)
 - [x] switch to YAML as the default config format

For launch:

 - [ ] update PL documentation
 - [ ] update README
 - [ ] update CHANGELOG
 - [ ] cut a v0.8.0 branch
 - [ ] merge with `master`
 - [ ] tag `master` with v0.8.0
 - [ ] update Releases

**Comment by TxHawks** [comment]
I'm about to start a new big project, and I'd love to use Twig instead of Mustache, as well as some of the other features in `2.0.0`. 
Is the development of `2.0.0` at a stable enough state for beta testing, or should I stick to stable for the time being?

**Comment by dmolsen** [comment]
@TxHawks -

I think PL2 is stable enough. Brad is using it for a personal project. Using composer should make upgrading your project pretty easy as I push new changes. The one area from old PL that definitely doesn't work is watch. The "view all" views are pretty rough too. They have some extra UI stuff that I was planning to work on and style but haven't gotten too yet. You might want to tweak the Twig StyleguideKit views after you download them to clean out that stuff. 

Also, with Twig you basically only get the pattern partial syntax. Twig provides more support for including data in the `include` tag so I suggest you use native Twig conventions for things like pattern parameters and style modifiers. I'm _pretty_ sure that works but I haven't tested in ages. Their's been a lot of interest in Twig but no one has fired it up and provided feedback. I'd love to get some.

If you're going to use Twig please use the [Twig-specific development edition](https://github.com/pattern-lab/edition-php-twig-development). You don't have to update the git remotes or anything. That's really only for Brad and I. Note that it's a git clone of core because you'll be grabbing the `dev` branch. It might take a while so be patient.

FWIW, if you actually use it and file issues I'll get to them as fast as I can just so I can get some real feedback. Sort of hopeful I'm over my huge crunch at work and being sick more on than off this past three months.

**Comment by TxHawks** [comment]
@dmolsen -
Thanks for the quick reply. 

Watch is no big deal, as I use Grunt for for that anyway (that should still work, I think).

I'll give it a try, and if I manage to have an initial project going on without too much overhead, I'll definitely go for it. 

Just so I'm clear, I would need to first to install the [Twig-specific dev edition](https://github.com/pattern-lab/edition-php-twig-development) and then the [Twig StyleguideKit default](https://github.com/pattern-lab/styleguidekit-twig-default/)?

**Comment by dmolsen** [comment]
Finally implemented as PL2 in this repo.

**Comment by dennisfrank** [comment]
Yay! :smiley:
