### ISSUE TITLE
Features for v0.7.0 Release

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php#66]
For tracking progress on v0.7.0. Should be released mid-December. The issues I'd like to cover:
- [x] move `source/_patternlab-files` to `core/` for better upgradability (#45) ~~(needs docs)~~
- [x] move `config.ini.default` into `core/`
- [x] address caching issues for all pages (#56)
- [x] address caching issues for included JS/CSS files
- [x] pattern parameters (#62) ~~(needs docs)~~
- [x] more easily include global assets in patterns (#64) ~~(needs docs)~~
- [x] provide error messages for malformed JSON
- [x] watcher can start the auto-reload server on its own (#36)
- [x] pages should be defined by JSON and use templates for mark-up (#31)  ~~(needs docs)~~
- [x] hidden patterns should still be available with the partial syntax (#73)
- [x] extend `_listitems.js` in the same way as `_data.js` (#74) 
- [x] add an ID based on pattern partial to viewall & style guide divs (#77)
- [x] restyle annotations ~~(needs docs?)~~
- [x] make sure `_data.json` and `_listitems.json` share same attributes (#79)
- [x] qr code for easy linking for mobile devices (#33)
- [x] port fix from `v0.6.3` to `dev` for issue #87
- [x] finish cleaning up the styles/functionality for small screens (#54)
- [x] fix page follow bug on Chrome
- [x] make sure annotations are cleaned up a little (numbering, hiding notes)
- [x] port fix from `v0.6.4` to `dev` for issue #88 
- [x] add support for reverse lineages (#89)
- [x] make sure the watcher tracks file with underscores so it'll regenerate the site properly (e.g. header changes)
- [x] add a config option to turn off `cleanPublic()` ~~(needs docs)~~

For launch:
- [x] copy `public/styleguide` to `core/styleguide`
- [x] update PL documentation
- [x] update README
- [x] update CHANGELOG
- [x] cut a v0.7.0 branch
- [x] merge with `master`
- [x] tag `master` with v0.7.0
- [x] update Releases
